### ISSUE TITLE
Problem about Dataset preprocess...

### ISSUE THREAD

**Issue by RichardWang11** [he159ok/CLUR_UncertaintyEst_FewShot_TextCls#2]
Hi Jianfeng,
    I have some trouble that I could download the dataset "20newsgroup" from Homepage. But I did not know how to process it well. I try to write the preprocess.py to process that raw dataset. Unfortunately, it fails to run the code. I got the error message: Traceback (most recent call last):
"/content/drive/MyDrive/CLUR_UncertaintyEst_FewShot_TextCls/src/main_uncertainty.py", line 383, in <module>
    main()
"/content/drive/MyDrive/CLUR_UncertaintyEst_FewShot_TextCls/src/main_uncertainty.py", line 309, in main
    train_data, val_data, test_data, vocab = loader.load_dataset(args)
"/content/drive/MyDrive/CLUR_UncertaintyEst_FewShot_TextCls/src/dataset/loader.py", line 426, in load_dataset
    all_data = _load_json(args.data_path)
"/content/drive/MyDrive/CLUR_UncertaintyEst_FewShot_TextCls/src/dataset/loader.py", line 183, in _load_json
    if int(row['label']) not in label:
TypeError: list indices must be integers or slices, not str
So can you help me... Many Thanks!

**Comment by he159ok** [comment]
Hi Richard,

I have shared processed datasets, where the links are in the Readme file.

The processed dataset file has a format that each row is like below.
{"text": ["token1", "token2", ...], "label": label_id}

where the "token1", and "token2" in the list are the tokenized results via a tokenizer applicable to Fastext in the shared processed datasets. These files come from "https://github.com/YujiaBao/Distributional-Signatures", so I do not have the original texts except the med-domain dataset. 

If you want to use other tokenizers, you need to regenerate these processed datasets via the respective tokenizers. Because of no original texts, this means you might need your own data split, but it could be a solution if you want to use a model with a different tokenizer.

I hope this could help you.

**Comment by RichardWang11** [comment]
> Hi Richard,
> 
> I have shared processed datasets, where the links are in the Readme file.
> 
> The processed dataset file has a format that each row is like below. {"text": ["token1", "token2", ...], "label": label_id}
> 
> where the "token1", and "token2" in the list are the tokenized results via a tokenizer applicable to Fastext in the shared processed datasets. These files come from "https://github.com/YujiaBao/Distributional-Signatures", so I do not have the original texts except the med-domain dataset.
> 
> If you want to use other tokenizers, you need to regenerate these processed datasets via the respective tokenizers. Because of no original texts, this means you might need your own data split, but it could be a solution if you want to use a model with a different tokenizer.
> 
> I hope this could help you.

Hi Jianfeng,
  I have successfully executed the code with your help! Now I have some questions that suddenly come to my mind. First one is the "Uncertainty Ratio" e.g. 10%, 20%... which you mentioned in Table 1 in your paper, and that mapping which parameter in your Training stage on 20News. So I can adjust the parameter and I can get similar results. The second question will be a little difficult, in my view, it is astonishing to use fastText as word embedding' results better than to use BERT as word embedding. Can you explain why CLUR play a little low performance on BERT embeddings. From my point, I think BERT is an excellent MLM(Masked Language Model).

**Comment by he159ok** [comment]
Hi Richard,

For your first question, the uncertainty ratios are not the parameters and they are the metrics, which have been calculated in my code and you do not need to consider this one. In the output,  the values for the key of '1_0' are a 5-length list, they are F1 scores of 0%, 10%, 20%, 30%, and 40% uncertainty ratios respectively. 

For your second question, the BERT-based method uses a different data split compared to the data split in the FastText-based method. This is because the originally released BERT-based 20News tokens via "https://github.com/YujiaBao/Distributional-Signatures" might be no longer compatible with the HuggingFace. Please refer to "https://github.com/YujiaBao/Distributional-Signatures/issues/32#issuecomment-1002725954". As a result, I chose to have a new data split for BERT due to no available original texts as I explained below. Due to the different data split, it is hard to compare the two results from BERT and FastText directly.

> where the "token1", and "token2" in the list are the tokenized results via a tokenizer applicable to Fastext in the shared processed datasets. These files come from "https://github.com/YujiaBao/Distributional-Signatures", so I do not have the original texts except the med-domain dataset.

I hope this can answer your questions.
